########################################################
# Started Logging At: 2012-07-19 14:36:36
########################################################

import idlsave
bgpsc = idlsave.read('bolocat/bolocat_v2.0_culled.sav')
bgpsc.shape
bgpsc.bgps_culled
bgpsc.bgps_culled.shape
bgpsc.bgps_culled.glon_peak
bgpsc.bgps_culled['GLON_PEAK']
bgpsc.bgps_culled['GLON_MAX']
get_ipython().magic(u"run ~/work/bgps_pipeline/analysis/bolocat_vs_longitude.py")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
bgpsv1
get_ipython().magic(u"paste")
bgpsv1.columns
figure(1)
clf()
hist(bgpsv2['GLON_MAX']-(360*bgpsv2['GLON_MAX'] > 180),bins=linspace(-10,90,101),histtype='step')
hist(bgpsv1['glon_peak']-(360*bgpsv1['glon_peak'] > 180),bins=linspace(-10,90,101),histtype='step')
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
draw()
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
len(glon_V1)
len(glon_v1)
len(glon_v2)
help(hist2d)
histogram2d 
help(histogram2d)
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
help(imshow)
get_ipython().magic(u"paste")
glon_v2
glon_v2.min()
bgpsv2['GLON_MAX']
bgpsv2['GLON_MAX'].max90
bgpsv2['GLON_MAX'].max()
bgpsv2['GLON_MAX'][bgpsv2['GLON_MAX'] > 350]
get_ipython().magic(u"paste")
glon_v2.min()
((glon_v2>-11)*(glon_v2<0)).sum()
figure(1)
hist(glon_v2,bins=linspace(-10,90,101),histtype='step',color='k',label='v2.0')
draw()
get_ipython().magic(u"run ~/work/bgps_pipeline/analysis/bolocat_vs_longitude.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/analysis/bolocat_vs_longitude.py")
matplotlib._pylab_helpers.Gcf.get_all_fig_managers()
F1,F2,F3 = matplotlib._pylab_helpers.Gcf.get_all_fig_managers()
F1.key_press 
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
glon_v1 = bgpsv1['glon_peak']-360*(bgpsv1['glon_peak'] > 180)
((glon_v1>-11)*(glon_v1<0)).sum()
draw()
xec1
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
notculled = idlsave.read('/Volumes/disk2/data/bgps/releases/v2.0/final/bolocat/bolocat_v2.0.sav').bgps
get_ipython().magic(u"paste")
glon_v2_notculled = notculled['GLON_MAX']-360*(glon_v2_notculled['GLON_MAX'] > 180)
glon_v2_notculled = notculled['GLON_MAX']-360*(notculled['GLON_MAX'] > 180)
get_ipython().magic(u"paste")
plot(glon_v2,bgpsv2['GLAT_MAX'],',')
plot(glon_v2_notculled,notculled['GLAT_MAX'],',')
plot(glon_v2,bgpsv2['GLAT_MAX'],',')
get_ipython().magic(u"run ~/work/bgps_pipeline/analysis/bolocat_vs_longitude.py")
plot(glon_v2,bgpsv2['GLAT_MAX'],',')
get_ipython().magic(u"paste")
axis([-5,5,-1,1])
get_ipython().magic(u"paste")
axis([-5,5,-1,1])
get_ipython().magic(u"paste")
axis([-5,5,-1,1])
bgpsv2.shape
draw()
figure(1); draw()
get_ipython().magic(u"paste")
colorbar()
help(colorbar)
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
plot(glon_v1,bgpsv1['glat_peak'],'g,')
get_ipython().magic(u"paste")
bgpsv2.dtype.names
bgpsv2.npix
help(np.bincount)
npix_glon_v2 = np.bincount(glon_v2, weights=bgpsv2['npix'])
npix_glon_v1 = np.bincount(glon_v1, weights=bgpsv1['npix'])
bgpsv1.columns
bgpsv1sav = idlsave.read('/Volumes/disk2/data/bgps/releases/v1.0/v1.0.2/bgps.v10.dat')
bgpsv1sav.bgps.shape
bgpsv1.shape
bgpsv1sav.bgps.dtype.names
get_ipython().magic(u"paste")
help(np.bincount)
help(np.digitize)
npix_glon_v2 = np.histogram(glon_v2, weights=bgpsv2['npix'])
npix_glon_v1 = np.histogram(glon_v1, weights=bgpsv1['npix'])
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
draw()
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
help(hist)
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
import plfit
from agpy import plfit
pf = plfit.plfit.plfit((bgpsv2['flux']))
pf = plfit.plfit.plfit(bgpsv2['flux'])
bgpsv2['flux']
bgpsv2['flux'].astype('float')
array(bgpsv2['flux'])
pf = plfit.plfit.plfit(array(bgpsv2['flux']))
pf = plfit.plfit(array(bgpsv2['flux']))
bgpsv2['flux']
pf = plfit.plfit.plfit(array(bgpsv2['flux'][bgpsv2['flux']==bgpsv2['flux']))
pf = plfit.plfit.plfit(array(bgpsv2['flux'][bgpsv2['flux']==bgpsv2['flux']]))
pf = plfit.plfit(array(bgpsv2['flux'][bgpsv2['flux']==bgpsv2['flux']]))
np.seterr(all='ignore')
pf = plfit.plfit(array(bgpsv2['flux'][bgpsv2['flux']==bgpsv2['flux']]))
pf.plfit()
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
l30 = (bolocat['glon_max'] < 31)*(bolocat['glon_max'] > 30)
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
show()
get_ipython().system(u"ls -F /Users/adam/work/bolocam/bolocat/")
p._alpha
p._alphaerr
print "%20s %10.3f %10.3f %10.3f %10.3f" % (name,p._alpha,p._alphaerr,p._ks,p._ks_prob)
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v2_powerlaws.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v2_powerlaws.py")
show()
get_ipython().magic(u"paste")
v2plfits.close()
pl._xmin
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v2_powerlaws.py")
get_ipython().magic(u"paste")
help(hist)
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
help(hist)
help(hist)
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
bolocat['flux'].max()
10**2.1
log10(292)
bolocat['flux_40'].max()
bolocat['flux_40'].min()
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v2_powerlaws.py")
    savefig('/Users/adam/work/bolocam/bolocat/bolocatv2_histograms.png')
savefig('/Users/adam/work/bolocam/bolocat/bolocatv2_histograms.png')
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
get_ipython().magic(u"paste")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v2_powerlaws.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v2_powerlaws.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
plalpha
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v2_powerlaws.py")
get_ipython().magic(u"paste")
get_ipython().magic(u"run ~/work/bgps_pipeline/bolocat/bolocat_v1_powerlaws.py")
bolocat.columns
bolocat.dtype.names
get_ipython().magic(u"paste")
draw()
get_ipython().magic(u"paste")
draw()
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
get_ipython().magic(u"paste")
bgpsv1['RAD_AS'].max()
nanmax(bgpsv1['RAD_AS'])
nanmax(bgpsv1['RAD_AS_NODC'])
bgpsv1.dtype.names
get_ipython().magic(u"pinfo2 hist")
??gca().hist
ax=gca()
get_ipython().magic(u"pinfo2 ax.hist")
get_ipython().magic(u"pinfo ax")
reload(matplotlib)
reload(matplotlib.axis)
reload(matplotlib.pylab)
from matplotlib.pylab import *
